extends: default

yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

rules:
  document-start: disable
  empty-lines:
    max: 1
  line-length:
    level: warning
    allow-non-breakable-inline-mappings: true
