name: redmine_kroki
include:
  - compose.kroki.yml
services:
  redmine5:
    build:
      context: .
      args:
        TAG: 5-alpine
        THEME_PATH: /usr/src/redmine/public/themes
    ports:
      - 8085:3000
    environment:
      REDMINE_PLUGINS_MIGRATE: true
    volumes:
      - ./src:/usr/src/redmine/plugins/redmine_kroki/
      - data-v5:/usr/src/redmine/sqlite/
    restart: on-failure:3

  redmine6:
    build:
      context: .
      args:
        TAG: 6-alpine
        THEME_PATH: /usr/src/redmine/themes
    ports:
      - 8086:3000
    environment:
      REDMINE_PLUGINS_MIGRATE: true
    volumes:
      - ./src:/usr/src/redmine/plugins/redmine_kroki/
      - data-v6:/usr/src/redmine/sqlite/
    restart: on-failure:3

volumes:
  data-v5:
  data-v6:
