name: redmine_kroki_test
include:
  - compose.kroki.yml
services:
  redmine:
    image: redmine:5-alpine
    environment:
      RAILS_ENV: test
    volumes:
      - ./src:/usr/src/redmine/plugins/redmine_kroki
      - ./database.yml:/usr/src/redmine/config/database.yml
