'on':
  push:
    paths-ignore:
      - '.editorconfig'
      - '.github/ISSUE_TEMPLATE/**'
      - '**.md'
      - 'doc/**'

permissions:
  contents: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Yamllint
        uses: karancode/yamllint-github-action@v2.1.1
        with:
          yamllint_config_filepath: .yamllint.yml
          yamllint_strict: true

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: scripts/test.sh

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    needs: [lint, test]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bundle
        run: |
          mv src redmine_kroki
          zip -r redmine_kroki.zip redmine_kroki
          zip -d redmine_kroki.zip redmine_kroki/test
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: redmine_kroki.zip
          tag_name: ${{ github.ref_name }}
