name: Publish

on:
  push:
    tags:
      - '*'
permissions:
  contents: write
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Bundle src directory as redmine_kroki.zip
        run: zip -r redmine_kroki.zip src

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: redmine_kroki.zip
          tag_name: ${{ github.ref_name }}
